site_name: embodied-ai
site_description: a framework for embodied-ai research
site_url: https://github.com/REDACTED_ORG/embodied-ai

theme:
  name: material
  palette:
    primary: blue
    accent: grey
  logo:
  favicon:
  highlightjs: true
  hljs_languages:
  - python
  - typescript
  - json


repo_name: REDACTED_ORG/embodied-ai
repo_url: https://github.com/REDACTED_ORG/embodied-ai
edit_uri: edit/master/docs/

nav:
- Overview: README.md
- Getting started:
  - Run your first experiment: overview/running-your-first-experiment.md
  - Primary abstractions: overview/abstractions.md
  - Defining an experiment: overview/defining-an-experiment.md
- Tutorials:
  - Third-party environments (MiniGrid): tutorials/minigrid-tutorial.md
  - Training a PointNav model in RoboTHOR: tutorials/training-a-pointnav-model.md
  - Training a PointNav model in iTHOR or Habitat: tutorials/transfering-to-a-different-environment-framework.md
  - Changing rewards and losses: tutorials/changing-rewards-and-losses.md
  - Defining a new model: tutorials/defining-a-new-model.md
  - Defining a new Task: tutorials/defining-a-new-task.md
- Projects using embodied-ai:
  - BabyAI Baselines: projects/babyai_baselines/README.md
- Roadmap: ROADMAP.md
- Contributing: CONTRIBUTING.md
- Licence: LICENSE.md
- FAQ: overview/FAQ.md
- API:
  - constants: api/constants.md
  - extensions:
    - rl_babyai:
      - babyai_scripts:
        - truncate_expert_demos: api/extensions/rl_babyai/babyai_scripts/truncate_expert_demos.md
        - get_instr_length_percentiles: api/extensions/rl_babyai/babyai_scripts/get_instr_length_percentiles.md
        - download_babyai_expert_demos: api/extensions/rl_babyai/babyai_scripts/download_babyai_expert_demos.md
      - babyai_constants: api/extensions/rl_babyai/babyai_constants.md
      - babyai_models: api/extensions/rl_babyai/babyai_models.md
      - babyai_tasks: api/extensions/rl_babyai/babyai_tasks.md
    - rl_minigrid:
      - minigrid_tasks: api/extensions/rl_minigrid/minigrid_tasks.md
      - minigrid_environments: api/extensions/rl_minigrid/minigrid_environments.md
      - minigrid_sensors: api/extensions/rl_minigrid/minigrid_sensors.md
      - minigrid_models: api/extensions/rl_minigrid/minigrid_models.md
    - rl_lighthouse:
      - lighthouse_models: api/extensions/rl_lighthouse/lighthouse_models.md
      - lighthouse_environment: api/extensions/rl_lighthouse/lighthouse_environment.md
      - lighthouse_tasks: api/extensions/rl_lighthouse/lighthouse_tasks.md
      - lighthouse_sensors: api/extensions/rl_lighthouse/lighthouse_sensors.md
      - lighthouse_util: api/extensions/rl_lighthouse/lighthouse_util.md
  - models:
    - basic_models: api/models/basic_models.md
    - frcnn_tensor_object_nav_models: api/models/frcnn_tensor_object_nav_models.md
    - resnet_tensor_object_nav_models: api/models/resnet_tensor_object_nav_models.md
  - offpolicy_sync:
    - losses:
      - abstract_offpolicy_loss: api/offpolicy_sync/losses/abstract_offpolicy_loss.md
  - onpolicy_sync:
    - losses:
      - imitation: api/onpolicy_sync/losses/imitation.md
      - abstract_loss: api/onpolicy_sync/losses/abstract_loss.md
      - ppo: api/onpolicy_sync/losses/ppo.md
      - kfac: api/onpolicy_sync/losses/kfac.md
      - a2cacktr: api/onpolicy_sync/losses/a2cacktr.md
    - runner: api/onpolicy_sync/runner.md
    - light_engine: api/onpolicy_sync/light_engine.md
    - policy: api/onpolicy_sync/policy.md
    - vector_sampled_tasks: api/onpolicy_sync/vector_sampled_tasks.md
    - storage: api/onpolicy_sync/storage.md
  - projects:
    - framework_transfer_tutorial:
      - experiments:
        - pointnav_habitat_rgb_ddppo: api/projects/framework_transfer_tutorial/experiments/pointnav_habitat_rgb_ddppo.md
        - pointnav_ithor_rgb_ddppo: api/projects/framework_transfer_tutorial/experiments/pointnav_ithor_rgb_ddppo.md
    - objectnav_baselines:
      - experiments:
        - robothor:
          - objectnav_robothor_base: api/projects/objectnav_baselines/experiments/robothor/objectnav_robothor_base.md
          - objectnav_robothor_rgb_resnetgru_ddppo: api/projects/objectnav_baselines/experiments/robothor/objectnav_robothor_rgb_resnetgru_ddppo.md
          - objectnav_robothor_rgbd_resnetgru_ddppo: api/projects/objectnav_baselines/experiments/robothor/objectnav_robothor_rgbd_resnetgru_ddppo.md
          - objectnav_robothor_depth_resnetgru_ddppo: api/projects/objectnav_baselines/experiments/robothor/objectnav_robothor_depth_resnetgru_ddppo.md
        - ithor:
          - objectnav_ithor_rgbd_resnetgru_ddppo: api/projects/objectnav_baselines/experiments/ithor/objectnav_ithor_rgbd_resnetgru_ddppo.md
          - objectnav_ithor_depth_resnetgru_ddppo: api/projects/objectnav_baselines/experiments/ithor/objectnav_ithor_depth_resnetgru_ddppo.md
          - objectnav_ithor_rgb_resnetgru_ddppo: api/projects/objectnav_baselines/experiments/ithor/objectnav_ithor_rgb_resnetgru_ddppo.md
          - objectnav_ithor_base: api/projects/objectnav_baselines/experiments/ithor/objectnav_ithor_base.md
        - objectnav_base: api/projects/objectnav_baselines/experiments/objectnav_base.md
      - models:
        - object_nav_models: api/projects/objectnav_baselines/models/object_nav_models.md
    - babyai_baselines:
      - experiments:
        - go_to_local:
          - bc: api/projects/babyai_baselines/experiments/go_to_local/bc.md
          - dagger: api/projects/babyai_baselines/experiments/go_to_local/dagger.md
          - bc_teacher_forcing: api/projects/babyai_baselines/experiments/go_to_local/bc_teacher_forcing.md
          - ppo: api/projects/babyai_baselines/experiments/go_to_local/ppo.md
          - a2c: api/projects/babyai_baselines/experiments/go_to_local/a2c.md
          - base: api/projects/babyai_baselines/experiments/go_to_local/base.md
        - go_to_obj:
          - bc: api/projects/babyai_baselines/experiments/go_to_obj/bc.md
          - dagger: api/projects/babyai_baselines/experiments/go_to_obj/dagger.md
          - bc_teacher_forcing: api/projects/babyai_baselines/experiments/go_to_obj/bc_teacher_forcing.md
          - ppo: api/projects/babyai_baselines/experiments/go_to_obj/ppo.md
          - a2c: api/projects/babyai_baselines/experiments/go_to_obj/a2c.md
          - base: api/projects/babyai_baselines/experiments/go_to_obj/base.md
        - base: api/projects/babyai_baselines/experiments/base.md
    - pointnav_baselines:
      - experiments:
        - robothor:
          - pointnav_robothor_rgbd_simpleconvgru_ddppo: api/projects/pointnav_baselines/experiments/robothor/pointnav_robothor_rgbd_simpleconvgru_ddppo.md
          - pointnav_robothor_depth_simpleconvgru_ddppo: api/projects/pointnav_baselines/experiments/robothor/pointnav_robothor_depth_simpleconvgru_ddppo.md
          - pointnav_robothor_rgb_simpleconvgru_ddppo: api/projects/pointnav_baselines/experiments/robothor/pointnav_robothor_rgb_simpleconvgru_ddppo.md
          - pointnav_robothor_base: api/projects/pointnav_baselines/experiments/robothor/pointnav_robothor_base.md
        - habitat:
          - pointnav_habitat_rgb_simpleconvgru_ddppo: api/projects/pointnav_baselines/experiments/habitat/pointnav_habitat_rgb_simpleconvgru_ddppo.md
          - pointnav_habitat_rgbd_simpleconvgru_ddppo: api/projects/pointnav_baselines/experiments/habitat/pointnav_habitat_rgbd_simpleconvgru_ddppo.md
          - pointnav_habitat_base: api/projects/pointnav_baselines/experiments/habitat/pointnav_habitat_base.md
          - pointnav_habitat_depth_simpleconvgru_ddppo: api/projects/pointnav_baselines/experiments/habitat/pointnav_habitat_depth_simpleconvgru_ddppo.md
        - pointnav_base: api/projects/pointnav_baselines/experiments/pointnav_base.md
        - ithor:
          - pointnav_ithor_rgbd_simpleconvgru_ddppo: api/projects/pointnav_baselines/experiments/ithor/pointnav_ithor_rgbd_simpleconvgru_ddppo.md
          - pointnav_ithor_rgb_simpleconvgru_ddppo: api/projects/pointnav_baselines/experiments/ithor/pointnav_ithor_rgb_simpleconvgru_ddppo.md
          - pointnav_ithor_base: api/projects/pointnav_baselines/experiments/ithor/pointnav_ithor_base.md
          - pointnav_ithor_depth_simpleconvgru_ddppo: api/projects/pointnav_baselines/experiments/ithor/pointnav_ithor_depth_simpleconvgru_ddppo.md
      - models:
        - point_nav_models: api/projects/pointnav_baselines/models/point_nav_models.md
    - tutorials:
      - minigrid_tutorial: api/projects/tutorials/minigrid_tutorial.md
    - robothor_pointnav_tutorial:
      - experiments:
        - pointnav_robothor_rgb_ddppo: api/projects/robothor_pointnav_tutorial/experiments/pointnav_robothor_rgb_ddppo.md
  - rl_ai2thor:
    - ai2thor_environment: api/rl_ai2thor/ai2thor_environment.md
    - ithor_constants: api/rl_ai2thor/ithor_constants.md
    - object_nav:
      - tasks: api/rl_ai2thor/object_nav/tasks.md
      - task_samplers: api/rl_ai2thor/object_nav/task_samplers.md
    - ai2thor_sensors: api/rl_ai2thor/ai2thor_sensors.md
    - ai2thor_util: api/rl_ai2thor/ai2thor_util.md
  - rl_base:
    - experiment_config: api/rl_base/experiment_config.md
    - task: api/rl_base/task.md
    - sensor: api/rl_base/sensor.md
    - preprocessor: api/rl_base/preprocessor.md
    - distributions: api/rl_base/distributions.md
    - common: api/rl_base/common.md
  - rl_habitat:
    - habitat_constants: api/rl_habitat/habitat_constants.md
    - habitat_tasks: api/rl_habitat/habitat_tasks.md
    - habitat_sensors: api/rl_habitat/habitat_sensors.md
    - habitat_environment: api/rl_habitat/habitat_environment.md
    - habitat_preprocessors: api/rl_habitat/habitat_preprocessors.md
    - habitat_task_samplers: api/rl_habitat/habitat_task_samplers.md
    - scripts:
      - agent_demo: api/rl_habitat/scripts/agent_demo.md
      - make_map: api/rl_habitat/scripts/make_map.md
    - habitat_utils: api/rl_habitat/habitat_utils.md
  - rl_robothor:
    - robothor_preprocessors: api/rl_robothor/robothor_preprocessors.md
    - robothor_task_samplers: api/rl_robothor/robothor_task_samplers.md
    - robothor_environment: api/rl_robothor/robothor_environment.md
    - robothor_constants: api/rl_robothor/robothor_constants.md
    - robothor_tasks: api/rl_robothor/robothor_tasks.md
    - robothor_sensors: api/rl_robothor/robothor_sensors.md
    - robothor_viz: api/rl_robothor/robothor_viz.md
  - tests:
    - sync_algs_cpu:
      - test_to_to_obj_trains: api/tests/sync_algs_cpu/test_to_to_obj_trains.md
  - utils:
    - model_utils: api/utils/model_utils.md
    - experiment_utils: api/utils/experiment_utils.md
    - system: api/utils/system.md
    - cacheless_frcnn: api/utils/cacheless_frcnn.md
    - misc_utils: api/utils/misc_utils.md
    - viz_utils: api/utils/viz_utils.md
    - tensor_utils: api/utils/tensor_utils.md
    - cache_utils: api/utils/cache_utils.md
markdown_extensions:
- toc:
    permalink: '#'
- markdown.extensions.codehilite:
    guess_lang: true
- admonition
- codehilite
- extra
#extra_javascript:
#  - javascripts/extra.js
#plugins:
#  - search
#  - mkpdfs
